### ISSUE TITLE
Im stil getting this issue

### ISSUE THREAD

**Issue by dempile** [cgruver/okd4-single-node-cluster#2]
DEBUG Still waiting for the Kubernetes API: Get https://api.okd4-snc.snc.test:6443/version?timeout=32s: dial tcp 10.10.1.67:6443: connect: network is unreachable
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get https://api.okd4-snc.snc.test:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 10.10.1.67:6443: connect: network is unreachable

**Comment by cgruver** [comment]
Let me see your `/etc/named/zones/db.snc.test` file.

It's also possible that your VM is not connecting to the network properly.

Describe your setup.

Host machine, Network, etc...

**Comment by dempile** [comment]
here is the db.snc.test file

@       IN      SOA     snc-host.snc.test. admin.snc.test. (
             3          ; Serial
             604800     ; Refresh
              86400     ; Retry
            2419200     ; Expire
             604800 )   ; Negative Cache TTL
;
; name servers - NS records
    IN      NS     snc-host.snc.test.

; name servers - A records
snc-host.snc.test.         IN      A      10.1.1.69

; 10.1.0.0/16 - A records
okd4-snc-bootstrap.snc.test.  IN      A      10.10.1.68
okd4-snc-master.snc.test.     IN      A      10.10.1.67
etcd-0.okd4-snc.snc.test.              IN      A      10.10.1.67
*.apps.okd4-snc.snc.test.     IN      A      10.10.1.67
api.okd4-snc.snc.test.        IN      A      10.10.1.67
api-int.okd4-snc.snc.test.    IN      A      10.10.1.67

_etcd-server-ssl._tcp.okd4-snc.snc.test    86400     IN    SRV     0    10    2380    etcd-0.okd4-snc.snc.test.

**Comment by dempile** [comment]
Hi Mr Gruver, 
- ip a

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UP group default qlen 1000
    link/ether 52:54:00:fd:09:a9 brd ff:ff:ff:ff:ff:ff
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:fd:09:a9 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.69/16 brd 10.1.255.255 scope global noprefixroute br0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fefd:9a9/64 scope link 
       valid_lft forever preferred_lft forever
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:a1:11:61 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:a1:11:61 brd ff:ff:ff:ff:ff:ff
8: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:fd:11:a9 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fefd:11a9/64 scope link 
       valid_lft forever preferred_lft forever
9: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:d1:52:da brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fed1:52da/64 scope link 
       valid_lft forever preferred_lft forever

- 
@IP 10.1.1.69

- 
cat /etc/named/zones/db.snc.test 

@       IN      SOA     snc-host.snc.test. admin.snc.test. (
             3          ; Serial
             604800     ; Refresh
              86400     ; Retry
            2419200     ; Expire
             604800 )   ; Negative Cache TTL
;
; name servers - NS records
    IN      NS     snc-host.snc.test.

; name servers - A records
snc-host.snc.test.         IN      A      10.1.1.69

; 10.1.0.0/16 - A records
okd4-snc-bootstrap.snc.test.  IN      A      10.10.1.68
okd4-snc-master.snc.test.     IN      A      10.10.1.67
etcd-0.okd4-snc.snc.test.              IN      A      10.10.1.67
*.apps.okd4-snc.snc.test.     IN      A      10.10.1.67
api.okd4-snc.snc.test.        IN      A      10.10.1.67
api-int.okd4-snc.snc.test.    IN      A      10.10.1.67

_etcd-server-ssl._tcp.okd4-snc.snc.test    86400     IN    SRV     0    10    2380    etcd-0.okd4-snc.snc.test.

- virsh list 

 Id    Name                           State
----------------------------------------------------
 3     okd4-snc-bootstrap             running
 4     okd4-snc-master                running


- i cannot access the console of the 2 VMs

Thanks

**Comment by cgruver** [comment]
When you say you can't access the console of the VMs, do you mean that `virsh console okd4-snc-bootstrap` does not work?  Or do you mean that you cannot SSH to the VMs?

I do see an issue with your DNS A records.  You are missing the `api` and `api-int` entries for the bootstrap node.  This setup uses DNS round robin during the install.  Take a look at the sample file that I provided.

Your A records should look like this:

```
; 10.1.0.0/16 - A records
okd4-snc-bootstrap.snc.test. IN A 10.10.1.68
okd4-snc-master.snc.test. IN A 10.10.1.67
etcd-0.okd4-snc.snc.test. IN A 10.10.1.67
*.apps.okd4-snc.snc.test. IN A 10.10.1.67
api.okd4-snc.snc.test. IN A 10.10.1.67
api.okd4-snc.snc.test. IN A 10.10.1.68 ; remove-after-bootstrap
api-int.okd4-snc.snc.test. IN A 10.10.1.67
api-int.okd4-snc.snc.test. IN A 10.10.1.68 ; remove-after-bootstrap
```

**Comment by dempile** [comment]
yes, virsh console okd4-snc-bootstrap does not work, and i did not try SSH before.
I will change my DNS records and let you know
Thanks

**Comment by cgruver** [comment]
It is very odd that `virsh console` is not working.  That suggests something may be amiss with your libvirt configuration...  but I don't know what off the top of my head.

**Comment by dempile** [comment]
Still have the same problem, maybe it is the VM OS, I will try to change the VM and try again.

**Comment by cgruver** [comment]
Closing this.  Let me know if you have additional issues.
