### ISSUE TITLE
Bootstrap starts but master cannot get ignition config

### ISSUE THREAD

**Issue by markxnelson** [cgruver/okd4-single-node-cluster#9]
Hi @cgruver thanks for this great resource.  I have been trying to follow the instructions, but I am getting stuck at the openshift-install step.  Right before that, it says to restart bootstrap and master.  When I do that, bootstrap starts fine, but master gets stuck trying to get the config - see console below.  I have done this several times now, on multiple machines, and keep ending up in the same place. Are you able to offer any suggestions about what to check?  Thanks in advance

```
[    6.592213] coreos-installer-service[851]: coreos-installer install /dev/sda --ignition-url http://10.0.0.114/install/fcos/ignition/master.ign --insecure-ignition --firstboot-args rd
.neednet=1 net.ifnames=1 ifname=nic0:52:54:00:a4:fc:28 ip=10.0.0.150::10.0.0.1:255.255.255.0:okd4-snc-master.snc.test:nic0:none nameserver=10.0.0.114  --platform qemu
[    9.697397] coreos-installer-service[862]: Error: parsing arguments
[    9.698402] coreos-installer-service[862]: Caused by: downloading source Ignition config http://10.0.0.114/install/fcos/ignition/master.ign
[    9.700067] coreos-installer-service[862]: Caused by: sending request for 'http://10.0.0.114/install/fcos/ignition/master.ign'
[    9.701514] coreos-installer-service[862]: Caused by: error sending request for url (http://10.0.0.114/install/fcos/ignition/master.ign): error trying to connect: tcp connect error:
No route to host (os error 113)
[    9.703709] coreos-installer-service[862]: Caused by: error trying to connect: tcp connect error: No route to host (os error 113)
[    9.705125] coreos-installer-service[862]: Caused by: tcp connect error: No route to host (os error 113)
[    9.706272] coreos-installer-service[862]: Caused by: No route to host (os error 113)
```

**Comment by markxnelson** [comment]
The only thing I see that is a little odd is the con for my primary nic seems to have device "--" (none) on it - is that normal?

```
[root@snc-host okd4-snc]# nmcli con
NAME        UUID                                  TYPE      DEVICE 
br0         9c2ddccb-0447-4f02-994e-f097fc4ea8a6  bridge    br0    
virbr0      f2073875-8192-41bf-8c17-0b37d2d1cb95  bridge    virbr0 
br0-bind-1  71f55280-57cd-47b5-8e39-b6bdc15072d3  ethernet  ens3f0 
ens3f0      a3e1fac4-cb80-4b9f-a993-8d668fbe7389  ethernet  --     
```

**Comment by markxnelson** [comment]
Ok - I can curl the ignition file that it is looking for successfully from the host machine.

**Comment by cgruver** [comment]
Hey, let me know if you are still stuck with this.  If you can curl the ignition config it is at least being served properly.  But the Bootstrap node may not be setting up it's network properly.

**Comment by markxnelson** [comment]
Hi, thanks I am still stuck yeah.  I am out of ideas.  The bootstrap vm is getting the config fine, but the master fails with no route to host.  My only thought is that maybe the way their root volumes are created is slightly different somehow

**Comment by cgruver** [comment]
Hey, sorry for the delayed response...  #Dayjob...

Let me see the contents of `~/bin/setSncEnv.sh` and the output of `ip addr`

**Comment by markxnelson** [comment]
Thanks @cgruver - we managed to come up with an alternative, so I don't need to get this working any more.  Thanks for your help anyway :+1:
